name = "letterheads-world"
main = "src/index.js"
compatibility_date = "2026-09-01"
workers_dev = true

[[durable_objects.bindings]]
name = "WORLD"
class_name = "World"

[[durable_objects.bindings]]
name = "DIR"
class_name = "Directory"

[[durable_objects.bindings]]
name = "PAGE"
class_name = "Page"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["World"]

[[migrations]]
tag = "v2"
new_sqlite_classes = ["Directory"]

[[migrations]]
tag = "v3"
new_sqlite_classes = ["Page"]
