name = "letterheads-world"
main = "src/index.js"
compatibility_date = "2026-09-01"
workers_dev = true

[[durable_objects.bindings]]
name = "WORLD"
class_name = "World"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["World"]
